version: '3'

services:
  mysql:
    image: juankanh/rpi-mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASS}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASS}
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9999:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=${USER}
      - PMA_PASSWORD=${PASS}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASS}
    depends_on:
      - mysql

  catalog:
    image: juankanh/[name]:[tag]
    ports:
      - 8081:8080
    expose:
      - 8080
    environment:
      - NAMEBD=${DATABASE}
      - HOST=mysql
      - USER=${USER}
      - PASS=${PASS}
    depends_on:
      - mysql